### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by joshua-8** [A-Bielefeld/TMCSerial#1]
Dear @bread-wolf,
Thank you for this great library, I was able to use it to control a motor with a TMC7300 driver!
I'm interested in using this library (and your TMCField library) for a project, but I don't see a license in either library. Are you willing to clarify the license terms of this software? I'm hoping that you will generously allow for the use of this library within other opensource software projects.
Thank you for your efforts to build this library!
Sincerely,
@joshua-8

**Comment by bread-wolf** [comment]
Hi, I added the AGPLv3 License, you're good as long as you republish any changes or contribution done to the code (like you did by forking). I will also update the TMCField library.

**Comment by joshua-8** [comment]
Thank you!
