### ISSUE TITLE
trouble using both motors at once

### ISSUE THREAD

**Issue by joshua-8** [A-Bielefeld/TMCSerial#2]
First of all, thanks for making this library! I was able to control a motor using it and a TMC7300.
When I tried to control two motors I ran into an issue: writing to TMC7300_PWM_B would make motorA turn off, and vise versa.
I notice that writeField appears to work by reading the current register from the IC, then updating the field's part of the register. I also notice that in 5.2 of the [7300 datasheet](https://www.analog.com/media/en/technical-documentation/data-sheets/TMC7300_datasheet_rev1.08.pdf) the PWM registers are listed as write only. When I try and read the PWM fields I get a zero.
Writing to a field in a write only register appears to set the other fields contained in that register to zero.

If you have time and are willing to respond, do you have any suggestions for a strategy to fix this? I'm interested in contributing to this library if you would accept that.

Thank you,
- joshua-8

**Comment by bread-wolf** [comment]
I forgot this is an issue with first this generation of Trinamic UART chips. I dont like it, as the write-only prevents the read-modify-write operation from working, there is no reason to do that.

Thankfully this should no longer happen with more recent chips. To fix that with the TMC7300 you need to write the whole register at once.

I made the writeRegister and readRegister functions public to do that. You can use the TMCField.address attribute as argument. If you are writing higher abstraction code, I would suggest always saving the values for PWM_A and PWM_B as attributes to your driver, or motor class, so at each update, you rewrite both at once.

**Comment by joshua-8** [comment]
Thank you, this is very helpful
